# Generated by Django 4.1.7 on 2023-04-11 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0002_npc_user_alter_npc_age_alter_npc_alignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='user',
        ),
    ]
