# Generated by Django 4.1.7 on 2023-04-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('job', models.CharField(max_length=30)),
                ('quirk', models.CharField(max_length=150)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('race', models.CharField(max_length=30)),
                ('alignment', models.CharField(max_length=30)),
                ('dnd_class', models.CharField(max_length=30)),
            ],
        ),
    ]
