# Generated by Django 4.1.7 on 2023-04-06 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NPC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='npc',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='npc',
            name='alignment',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='npc',
            name='charisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='npc',
            name='constitution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='npc',
            name='dexterity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='npc',
            name='dnd_class',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='npc',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='npc',
            name='job',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='npc',
            name='quirk',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='npc',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='npc',
            name='wisdom',
            field=models.IntegerField(default=0),
        ),
    ]
